# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAWEveKWCJdBJ9QcwxXNULBnb35HOUA8
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/h.csv')

df.isna().sum()

unique_count = df['ocean_proximity'].nunique()
print(unique_count)

df.median_house_value

df.median_house_value[df.ocean_proximity == 'NEAR BAY'].mean()